### ISSUE TITLE
Queue env var inconsistently named

### ISSUE THREAD

**Issue by eldeal** [ONSdigital/sdx-receipt-ctp#4]
https://github.com/ONSdigital/sdx-receipt-ctp/blob/5d31bd6d27f9785d935ff14722575a9a30b9bd96/app/settings.py#L18

Should be RABBIT_QUEUE to be consistent with other repos, or a more descriptive name - definitely no MQ though.

**Comment by necrophonic** [comment]
Covered elsewhere
